[package]
name = "trace-reader"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
common = { path = "../common" }
streaming-types = { path = "../streaming-types" }

itertools = "0.11.0"
rand = "0.8.5"
anyhow = "1.0"
chrono = "0.4.22"
env_logger = "0.10"
kagiyama = "0.3.0"
log = "0.4"
dotenv = "0.15.0"
rdkafka.workspace = true
clap.workspace = true
tokio.workspace = true

[dev-dependencies]
serde = "1.0.164"
