[package]
name = "kafka-daq-report"
version = "0.1.0"
license = "GPL-3.0-only"
edition = "2021"

[dependencies]
common = { path = "../common" }
streaming-types = { path = "../streaming-types" }

anyhow = "1.0"
chrono = "0.4.22"
clap = { version = "4.0", features = ["derive"] }
crossterm = "0.27.0"
env_logger = "0.10"
# hdf5 = { version = "0.8.1", features = ["static"] }
hdf5 = { git = "https://github.com/aldanor/hdf5-rust", rev = "26046fb4900ec38afd2a1c0494cff688b288662e", features = ["static"] }
lazy_static = "1.4.0"
log = "0.4"
ndarray = "0.15.4"
ratatui = "0.23.0"
rdkafka = { version = "0.34.0", features = ["cmake-build", "ssl-vendored", "gssapi-vendored", "sasl"] }
tokio = { version = "1.24", features = ["macros", "rt-multi-thread"] }
